import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="vi">
      <body>
        <Theme accentColor="teal" radius="full">
          {children}
        </Theme>
      </body>
    </html>
  );
}
